apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-data
  labels:
    type: local
spec:
  accessModes:   
    - ReadWriteOnce
  capacity:
    storage: 20Gi
  hostPath:
    path: "/mnt/data/elastic"
